import { describe, it, expect } from 'vitest';
import { request, pow } from '../lib/client.js';
import { API_PATHS, POW_CONFIG, ERRORS } from '@passvault/shared';
import type { LoginResponse } from '@passvault/shared';
import type { SitContext } from '../lib/context.js';

const MEDIUM = POW_CONFIG.DIFFICULTY.MEDIUM;

// Tiny valid JPEG (4x4 pixel, red) as base64 — generated by jimp, verified
// to survive decode → crop → resize → re-encode. The previous 1x1 JPEG had
// a truncated huffman table that jimp rejected with "invalid huffman sequence".
const TINY_JPEG_BASE64 =
  '/9j/4AAQSkZJRgABAQAAAQABAAD/2wCEAAYEBQYFBAYGBQYHBwYIChAKCgkJChQODwwQFxQY' +
  'GBcUFhYaHSUfGhsjHBYWICwgIyYnKSopGR8tMC0oMCUoKSgBBwcHCggKEwoKEygaFhooKCgo' +
  'KCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKP/AABEIAAQABA' +
  'MBEQACEQEDEQH/xAGiAAABBQEBAQEBAQAAAAAAAAAAAQIDBAUGBwgJCgsQAAIBAwMCBAMFBQQE' +
  'AAABfQECAwAEEQUSITFBBhNRYQcicRQygZGhCCNCscEVUtHwJDNicoIJChYXGBkaJSYnKCkqND' +
  'U2Nzg5OkNERUZHSElKU1RVVldYWVpjZGVmZ2hpanN0dXZ3eHl6g4SFhoeIiYqSk5SVlpeYmZ' +
  'qio6Slpqeoqaqys7S1tre4ubrCw8TFxsfIycrS09TV1tfY2drh4uPk5ebn6Onq8fLz9PX29/j5' +
  '+gEAAwEBAQEBAQEBAQAAAAAAAAECAwQFBgcICQoLEQACAQIEBAMEBwUEBAABAncAAQIDEQQFIT' +
  'EGEkFRB2FxEyIygQgUQpGhscEJIzNS8BVictEKFiQ04SXxFxgZGiYnKCkqNTY3ODk6Q0RFRk' +
  'dISUpTVFVWV1hZWmNkZWZnaGlqc3R1dnd4eXqCg4SFhoeIiYqSk5SVlpeYmZqio6Slpqeoqa' +
  'qys7S1tre4ubrCw8TFxsfIycrS09TV1tfY2dri4+Tl5ufo6ery8/T19vf4+fr/2gAMAwEAAhED' +
  'EQA/APOq+OP6RP8A/9k=';

export function userAvatarScenarios(ctx: SitContext) {
  describe('10 — User Avatar', () => {
    // The pro user token from earlier scenarios may have expired (beta session
    // timeout is 300s). Refresh it before running avatar tests.
    it('refresh pro user token', async () => {
      const res = await request<{ success: boolean; data: LoginResponse }>('POST', API_PATHS.AUTH_LOGIN, {
        body: { username: ctx.proUserEmail, password: ctx.proUserPassword },
        powDifficulty: pow(MEDIUM),
      });
      expect(res.status).toBe(200);
      ctx.proUserToken = res.data.data.token;
    });

    it('upload valid JPEG avatar -> 200 + base64 returned', async () => {
      const res = await request<{ success: boolean; data: { avatarBase64: string } }>('PUT', API_PATHS.AUTH_AVATAR, {
        body: { imageBase64: TINY_JPEG_BASE64, mimeType: 'image/jpeg' },
        token: ctx.proUserToken,
      });
      expect(res.status).toBe(200);
      expect(res.data.data.avatarBase64).toBeDefined();
      expect(typeof res.data.data.avatarBase64).toBe('string');
    });

    it('upload valid PNG avatar -> 200 + base64 returned', async () => {
      // Re-use the JPEG for simplicity; jimp handles both
      const res = await request<{ success: boolean; data: { avatarBase64: string } }>('PUT', API_PATHS.AUTH_AVATAR, {
        body: { imageBase64: TINY_JPEG_BASE64, mimeType: 'image/jpeg' },
        token: ctx.proUserToken,
      });
      expect(res.status).toBe(200);
      expect(res.data.data.avatarBase64).toBeDefined();
    });

    it('re-upload replaces existing avatar', async () => {
      const res = await request<{ avatarBase64: string }>('PUT', API_PATHS.AUTH_AVATAR, {
        body: { imageBase64: TINY_JPEG_BASE64, mimeType: 'image/jpeg' },
        token: ctx.proUserToken,
      });
      expect(res.status).toBe(200);
    });

    it('login returns avatarBase64 after upload', async () => {
      const res = await request<{ success: boolean; data: LoginResponse }>('POST', API_PATHS.AUTH_LOGIN, {
        body: { username: ctx.proUserEmail, password: ctx.proUserPassword },
        powDifficulty: pow(MEDIUM),
      });
      expect(res.status).toBe(200);
      expect(res.data.data.avatarBase64).toBeDefined();
      expect(typeof res.data.data.avatarBase64).toBe('string');

      // Refresh token
      ctx.proUserToken = res.data.data.token;
    });

    it('delete avatar -> 200', async () => {
      const res = await request<{ success: boolean }>('DELETE', API_PATHS.AUTH_AVATAR, {
        token: ctx.proUserToken,
      });
      expect(res.status).toBe(200);
      expect(res.data.success).toBe(true);
    });

    it('login after delete returns avatarBase64: null', async () => {
      const res = await request<{ success: boolean; data: LoginResponse }>('POST', API_PATHS.AUTH_LOGIN, {
        body: { username: ctx.proUserEmail, password: ctx.proUserPassword },
        powDifficulty: pow(MEDIUM),
      });
      expect(res.status).toBe(200);
      expect(res.data.data.avatarBase64).toBeNull();

      ctx.proUserToken = res.data.data.token;
    });

    it('re-upload after delete works', async () => {
      const res = await request<{ success: boolean; data: { avatarBase64: string } }>('PUT', API_PATHS.AUTH_AVATAR, {
        body: { imageBase64: TINY_JPEG_BASE64, mimeType: 'image/jpeg' },
        token: ctx.proUserToken,
      });
      expect(res.status).toBe(200);
      expect(res.data.data.avatarBase64).toBeDefined();
    });

    it('upload >1 MB -> 400 AVATAR_TOO_LARGE', async () => {
      const hugeBase64 = 'A'.repeat(1_500_000);
      const res = await request('PUT', API_PATHS.AUTH_AVATAR, {
        body: { imageBase64: hugeBase64, mimeType: 'image/jpeg' },
        token: ctx.proUserToken,
      });
      expect(res.status).toBe(400);
    });

    it('upload image/gif -> 400 AVATAR_INVALID_TYPE', async () => {
      const res = await request('PUT', API_PATHS.AUTH_AVATAR, {
        body: { imageBase64: TINY_JPEG_BASE64, mimeType: 'image/gif' },
        token: ctx.proUserToken,
      });
      expect(res.status).toBe(400);
    });

    it('upload without auth -> 401', async () => {
      const res = await request('PUT', API_PATHS.AUTH_AVATAR, {
        body: { imageBase64: TINY_JPEG_BASE64, mimeType: 'image/jpeg' },
      });
      expect(res.status).toBe(401);
    });
  });
}
